name: LightningDeath
version: 1.3
main: me.mrxbox98.LightningDeath.LightningDeathPlugin

permissions:
  CauseLightning:
    description: lets a player summon lightning whenever they kill an entity
    default: true